# Generated by Django 5.2.3 on 2026-03-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0002_alter_order_tracker_created_by_alter_order_opened_by_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="table",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.RemoveField(
            model_name="order",
            name="opened_by",
        ),
        migrations.RemoveField(
            model_name="order_tracker",
            name="order",
        ),
        migrations.RemoveField(
            model_name="order_tracker",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="DiningTable",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Order_Tracker",
        ),
    ]
