# Generated by Django 5.2.3 on 2026-03-15 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Tables", "0003_delete_item_remove_order_tracker_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("item_picture", models.ImageField(upload_to="menuItems/")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="Tables.diningtable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Bill_Total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Billed_to", models.CharField(max_length=255)),
                ("VAT", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "Discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("Billing_Date", models.DateTimeField(auto_now_add=True)),
                (
                    "Order_ins",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Order.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_Tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("special_note", models.TextField(blank=True, null=True)),
                (
                    "order_items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Order.menu"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrderItem",
                to="Order.order_tracker",
            ),
        ),
    ]
