# Generated by Django 5.2.3 on 2026-03-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0003_rename_order_tracker_order_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="Order_ins",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrderObj",
                to="Order.order",
            ),
        ),
    ]
