# Generated by Django 5.2.3 on 2026-03-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0004_alter_bill_order_ins"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bill",
        ),
    ]
