# Generated by Django 5.2.3 on 2026-03-15 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0005_delete_bill"),
        ("Tables", "0003_delete_item_remove_order_tracker_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="table",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderTable",
                to="Tables.diningtable",
            ),
        ),
    ]
