# Generated by Django 5.2.3 on 2026-03-21 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0008_alter_order_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="Tip",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(49),
                ],
            ),
        ),
    ]
