# Generated by Django 5.2.3 on 2026-03-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0009_alter_order_tip"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[("active", "active"), ("completed", "completed")],
                default="active",
                max_length=50,
            ),
        ),
    ]
