# Generated by Django 5.2.3 on 2026-03-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0011_alter_order_waiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="category",
            field=models.CharField(
                choices=[
                    ("Main Course", "Main Course"),
                    ("Appetizer", "Appetizer"),
                    ("Dessert", "Dessert"),
                    ("Beverage", "Beverage"),
                    ("Side", "Side Dish"),
                ],
                default="Main Course",
                max_length=20,
            ),
        ),
    ]
