# Generated by Django 5.2.3 on 2026-04-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0012_menu_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="item_picture",
        ),
    ]
