# Generated by Django 5.2.3 on 2026-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0014_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
