# Generated by Django 5.2.3 on 2026-03-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tables", "0002_item_order_order_tracker"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.RemoveField(
            model_name="order_tracker",
            name="order",
        ),
        migrations.RemoveField(
            model_name="order_tracker",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Order_Tracker",
        ),
    ]
