# Generated by Django 5.2.3 on 2026-03-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tables", "0003_delete_item_remove_order_tracker_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diningtable",
            name="capacity",
            field=models.IntegerField(default=4, max_length=10),
        ),
        migrations.AddField(
            model_name="diningtable",
            name="status",
            field=models.CharField(
                choices=[("AVAIALABLE", "AVAIALABLE"), ("OCCUPIED", "OCCUPIED")],
                default="AVAILABLE",
            ),
        ),
    ]
