# Generated by Django 5.2.3 on 2026-03-28 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tables", "0004_diningtable_capacity_diningtable_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diningtable",
            name="capacity",
            field=models.IntegerField(
                default=4,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(2),
                ],
            ),
        ),
    ]
