# Generated by Django 5.2.3 on 2026-03-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tables", "0005_alter_diningtable_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diningtable",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "AVAILABLE"), ("OCCUPIED", "OCCUPIED")],
                default="AVAILABLE",
            ),
        ),
    ]
