# Generated by Django 5.2.3 on 2026-03-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tables", "0007_alter_diningtable_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diningtable",
            name="status",
            field=models.CharField(
                choices=[("available", "available"), ("occupied", "occupied")],
                default="available",
            ),
        ),
    ]
