# Generated by Django 5.2.3 on 2026-04-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Billing", "0002_bill_subtottal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="subtottal",
            new_name="subtotal",
        ),
    ]
